module SizeValues
  SCREEN_WIDTH = 640
  SCREEN_HEIGHT = 480
  BALL_STEP = 5
  CENTER_X = SCREEN_WIDTH/2
  CENTER_Y = SCREEN_HEIGHT/2
  BALL_DIAMETER = 15
  PLAYER_WIDTH = 66
  PLAYER_HEIGHT = 13
  PLAYER_STARTING_X = 300
  PLAYER_STARTING_Y = 420
  PLAYER_STEP = 8
  BONUS_WIDTH = 25
  BONUS_HEIGHT = 12
  BONUS_STEP = 2
  CONTACT_BUFFER = 5
  ANGLE_FORMULA_MAX_ANGLE = 85
	BRICK_WIDTH = 64
  BRICK_HEIGHT = 16
  VICTORY_IMAGE_WIDTH = 360
  VICTORY_IMAGE_HEIGHT = 112
  LOSS_IMAGE_WIDTH = 324
  LOSS_IMAGE_HEIGHT = 112
end